// <auto-generated />
using BT29_10.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BT29_10.Migrations
{
    [DbContext(typeof(StudentDbContext))]
    [Migration("20251029094339_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BT29_10.Models.Studen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Studens");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 20,
                            Name = "Alice"
                        },
                        new
                        {
                            Id = 2,
                            Age = 22,
                            Name = "Bob"
                        },
                        new
                        {
                            Id = 3,
                            Age = 21,
                            Name = "Charlie"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
