// <auto-generated />
using Lab09_v2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lab09_v2.Migrations
{
    [DbContext(typeof(nthDbContext))]
    [Migration("20251017091727_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lab09_v2.Models.nthLoaiSanPham", b =>
                {
                    b.Property<long>("nthId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("nthId"));

                    b.Property<string>("nthMaLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nthTenLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("nthTrangThai")
                        .HasColumnType("bit");

                    b.HasKey("nthId");

                    b.ToTable("nth_LoaiSanPham");
                });

            modelBuilder.Entity("Lab09_v2.Models.nthSanPham", b =>
                {
                    b.Property<long>("nthId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("nthId"));

                    b.Property<decimal>("nthDonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("nthHinhAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("nthLoaiId")
                        .HasColumnType("bigint");

                    b.Property<string>("nthMaSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("nthSoLuong")
                        .HasColumnType("int");

                    b.Property<string>("nthTenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("nthId");

                    b.HasIndex("nthLoaiId");

                    b.ToTable("nth_SanPham");
                });

            modelBuilder.Entity("Lab09_v2.Models.nthSanPham", b =>
                {
                    b.HasOne("Lab09_v2.Models.nthLoaiSanPham", "LoaiSanPham")
                        .WithMany("SanPhams")
                        .HasForeignKey("nthLoaiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiSanPham");
                });

            modelBuilder.Entity("Lab09_v2.Models.nthLoaiSanPham", b =>
                {
                    b.Navigation("SanPhams");
                });
#pragma warning restore 612, 618
        }
    }
}
